$("div").css("background-color", "blue");
$("#food").css("border", "green solid 8px");
$(".fun").css("fontSize", "48px");
$("div:first-of-type").css("color", "orange");
// $("img").attr("src", "https://i.imgur.com/D9HkrX4.gif");
// $("input").attr("type","color");
// $("input").val("Did you see the");
// $("select").val();
//$("img").addClass("indicator");
//$("img").removeClass("indicator");
//$("img").toggleClass("indicator");